language: r
cache: packages
sudo: false

r:
  - devel
  - release

r_packages:
  - covr
  
after_success:
  - Rscript -e 'covr::codecov()'

notifications:
  email:
    on_success: lg390@cam.ac.uk
    on_failure: lg390@cam.ac.uk

